### ISSUE TITLE
Standard Pressure Level Formatting

### ISSUE THREAD

**Issue by Phantom139** [dniloash/Pywinter#1]
Good Afternoon,

While trying to use this package to convert netCDF data from a NOAA PSL dataset (20CR V3) into WRF intermediate files, I encountered an error with one of the validation statements.

The issue occurs with winter.py ([L503](https://github.com/dniloash/Pywinter/blob/master/pywinter/winter.py#L503)), in which the pressure field length is checked to match that of the incoming data. The error I'm encountering is when directly loading the pressure count from an XArray into a numpy array as such:

```
TT = xarray.open_dataset(lnk_TT)
pres = TT["level"].values

winter_geo = winter.Geo0(lat, lon)
winter_t = winter.V3dp('TT', TT["air"][iStep].values[:,:,:], pres)
```

The statement errors out when trying to run len() on a single integer value obtained from the numpy ndarray which is the pres() variable. 

Unless there is a specific input formatting required here, I'd recommend simply dropping the len() statement and requiring the input of pres simply be a numpy ndarray object containing the pressure levels.

**Comment by dniloash** [comment]
Hello, you are right, thanks for pointing out that issue. I will check and correct as soon as possible.

**Comment by dniloash** [comment]
It's done, please upgrade a try again.
pip install -U pywinter

**Comment by Phantom139** [comment]
Yep, that seems to have addressed that error.

Thanks!
