### ISSUE TITLE
Order of latitudes in the netcdf file

### ISSUE THREAD

**Issue by GabrieleBentiv** [dniloash/Pywinter#12]
It should be highlighted in the quick setup guide that it is crucial to have the netcdf file with the latitudes ordered from the lower to the higher (degrees north), otherwise even though the corner is indicated correctly in the Geo function, the variables will be mirrored within that domain along the North-South dimension.

**Comment by dniloash** [comment]
Hello, that is correct. The latitude and longitude must be ordered from the lower to the higher in degrees north and degrees east, and the array data must be according to the respective coordinates. 
In the Geo functions, it is indicated that you must enter the SOUTH-EAST corner. But, for example, if the latitude is ordered from higher to lower and you do not want to reorder the data, you must enter the NORTH-EAST corner and also change the sign of the [dlat] parameter to a negative value. I understand that this can be a bit tricky in some cases. I will consider changing the parameter and asking for the full latitude and longitude vector. For now, I can highlight the topic in the setup guide.
Thanks.

**Comment by dniloash** [comment]
The topic has been highlighted in the setup guide and an example has been added.
