### ISSUE TITLE
How to make a single FILE:2024-01-01_00 with all the necessary varibales

### ISSUE THREAD

**Issue by numtas** [dniloash/Pywinter#13]
Hey, the examples given in the repos has shown how to make separate intermediate files for (2D) and (3D) variables, is it possible to make a single intermediate file for each time frame with all the necessary variables both 2d and 3d??

**Comment by dniloash** [comment]
Hi !, there is not difference, You only have to include the variables in the list. Yo can check the final example in the documentation (cinter section).
https://pywinter.readthedocs.io/en/latest/

**Comment by dniloash** [comment]
Close

**Comment by numtas** [comment]
Oh Thank you!
