### ISSUE TITLE
Undeclared variable in Geo1 constructor

### ISSUE THREAD

**Issue by jverdasca** [dniloash/Pywinter#2]
The constructor of Geo1 (winter.py) has the variable dx and dy (lines 732 and 733) that are not declared and the variables xx and yy (line 728) are not used, causing the error: NameError: name 'dx' is not defined

![Captura de ecrã de 2020-10-30 17-24-30](https://user-images.githubusercontent.com/73713137/97737538-0fc72e00-1ad5-11eb-93db-c292542522fe.png)

**Comment by dniloash** [comment]
Hello thanks for reporting that issue, please update and try again (pip install -U pywinter)
