### ISSUE TITLE
Geo5 object has no attribute nlats

### ISSUE THREAD

**Issue by jverdasca** [dniloash/Pywinter#4]
Hi!

Probably you remember me from last issue :P
I keep working with your library and I am verifying that when using Geo5, and I call the function "cinter", an instance of the Geo04 object is created with the Geo5 object instance (geoinfo), which later results in error "AttributeError: 'Geo5' object has no attribute 'nlats'" in the Geo04 function "set_atr".
I checked the data that I'm using but I can't get over that error. Could it be a library error?
I leaving here a print of the error for easier troubleshutting.

![Captura de ecrã de 2021-01-19 18-41-42](https://user-images.githubusercontent.com/73713137/105078844-76316c00-5a86-11eb-8a63-82d61c7e8726.png)

Thank you for your time and support

**Comment by dniloash** [comment]
Hello, It is library error, I have done a modification and I hope that it works.
You can update the lib (pip install -U pywinter) and try again.
Thanks for reporting that problem.

**Comment by jverdasca** [comment]
Hello,

Thank you for your time, fast response and support! :)
I updated the lib, but now it is giving me another error. Now it says "AttributeError: 'Geo5' object has no attribute 'tlat2'" in "set_atr" of object Geo05 when I call "cinter" function
I'm leaving here a print of the error for easier troubleshutting.

![Captura de ecrã de 2021-01-21 11-05-05 png](https://user-images.githubusercontent.com/73713137/105343010-fc5dc780-5bd8-11eb-99f3-b9786c6128a1.png)

**Comment by jverdasca** [comment]
Hello again
I am not sure how you are going to solve the issue "AttributeError: 'Geo5' object has no attribute 'tlat2'" that I have reported now, but can you please also check the "create_intermf" function of the "Interm" class. Line 141 probably should be "elif isinstance (self.geos, Geo05):" instead of "elif isinstance (self.geos, Geo03):", since this condition already exists on line 123

**Comment by dniloash** [comment]
Hello, you are right, new update includes the correction in the line 141.
Thank you for your contribution.
