### ISSUE TITLE
'Geo5' object has no attribute 'tlat2'

### ISSUE THREAD

**Issue by jverdasca** [dniloash/Pywinter#6]
Hello,

I'm using the latest version of pywinter and I got the error AttributeError: 'Geo5' object has no attribute 'tlat2' when using Geo5 object to create data for for Polar projection

I leaving here a print of the error for easier troubleshutting.

![pywinter_Geo5_error](https://user-images.githubusercontent.com/73713137/109163791-9cc38080-7771-11eb-938e-f427f2968332.png)

Thank you for your time and support!

**Comment by dniloash** [comment]
Hello, thanks for reporting the problem in the latest version.
The correction has been included. Please update and try again.
