### ISSUE TITLE
There is a serious bug on Windows

### ISSUE THREAD

**Issue by is-a-gamer** [dniloash/Pywinter#8]
May I ask if you plan to support Windows for this library?

https://github.com/dniloash/Pywinter/blob/389bd1198b25317ce911723b305a9ee193ed5056/pywinter/winter.py#L151

This file name will not be able to be stored on Windows

If you plan to support Windows, I suggest checking if the current machine is Windows. If so, then modify it to `.`

if you do not intend to support it, please close this issue directly

Thank you for your reply

**Comment by dniloash** [comment]
Hi, Not short term plans for full Windows support, but optional nocolons parameter in cinter function will be included (False by default). If true > self.rout+self.filen+'_'+self.hdat  )
